"""
Custom admin URL routes. All under /admin/ (Django admin is at /admin-django/).
"""
from django.urls import path

from . import views

urlpatterns = [
    path("", views.admin_home, name="admin_home"),
    path("users/", views.user_list, name="admin_user_list"),
    path("users/add/", views.user_add, name="admin_user_add"),
    path("users/<int:pk>/", views.user_detail, name="admin_user_detail"),
    path("users/<int:pk>/edit/", views.user_edit, name="admin_user_edit"),
    path("users/<int:pk>/delete/", views.user_delete, name="admin_user_delete"),
    path("roles/", views.role_list, name="admin_role_list"),
    path("roles/add/", views.role_add, name="admin_role_add"),
    path("roles/<int:pk>/edit/", views.role_edit, name="admin_role_edit"),
    path("customers/", views.customer_list, name="admin_customer_list"),
    path("customers/add/", views.customer_add, name="admin_customer_add"),
    path("customers/<int:pk>/", views.customer_detail, name="admin_customer_detail"),
    path("customers/<int:pk>/edit/", views.customer_edit, name="admin_customer_edit"),
    path("customers/<int:pk>/delete/", views.customer_delete, name="admin_customer_delete"),
    path("customers/<int:pk>/logo/", views.customer_logo_upload, name="admin_customer_logo_upload"),
    path("customers/<int:pk>/logo/delete/", views.customer_logo_delete, name="admin_customer_logo_delete"),
    path("customers/access/", views.customer_access_list, name="admin_customer_access_list"),
    path("customers/access/add/", views.customer_access_add, name="admin_customer_access_add"),
    path("customers/access/<int:pk>/edit/", views.customer_access_edit, name="admin_customer_access_edit"),
    path("portal-links/", views.portal_link_list, name="admin_portal_link_list"),
    path("portal-links/add/", views.portal_link_add, name="admin_portal_link_add"),
    path("portal-links/<int:pk>/edit/", views.portal_link_edit, name="admin_portal_link_edit"),
    path("announcements/", views.announcement_list, name="admin_announcement_list"),
    path("announcements/add/", views.announcement_add, name="admin_announcement_add"),
    path("announcements/<int:pk>/edit/", views.announcement_edit, name="admin_announcement_edit"),
    path("announcements/<int:pk>/delete/", views.announcement_delete, name="admin_announcement_delete"),
    path("notifications/", views.admin_notification_list, name="admin_notification_list"),
    path("notifications/create/", views.admin_notification_create, name="admin_notification_create"),
    path("notifications/<int:pk>/mark-read/", views.admin_notification_mark_read, name="admin_notification_mark_read"),
    path("network-devices/", views.redirect_to_devices, name="admin_network_device_list_redirect"),
    path("devices/", views.device_landing, name="admin_device_list"),
    path("devices/types/", views.device_type_list, name="admin_device_type_list"),
    path("devices/types/add/", views.device_type_add, name="admin_device_type_add"),
    path("devices/produkt/<slug:slug>/", views.device_type_detail, name="admin_device_type_detail"),
    path("devices/produkt/<slug:slug>/edit/", views.device_type_edit, name="admin_device_type_edit"),
    path("devices/produkt/<slug:type_slug>/instances/add/", views.device_instance_add, name="admin_device_instance_add"),
    path("devices/produkt/<slug:type_slug>/instances/<int:instance_pk>/edit/", views.device_instance_edit, name="admin_device_instance_edit"),
    path("devices/produkt/<slug:type_slug>/instances/<int:instance_pk>/delete/", views.device_instance_delete, name="admin_device_instance_delete"),
    path("devices/categories/", views.device_category_list, name="admin_device_category_list"),
    path("devices/categories/add/", views.device_category_add, name="admin_device_category_add"),
    path("devices/categories/<int:pk>/edit/", views.device_category_edit, name="admin_device_category_edit"),
    path("devices/manufacturers/", views.manufacturer_list, name="admin_manufacturer_list"),
    path("devices/manufacturers/add/", views.manufacturer_add, name="admin_manufacturer_add"),
    path("devices/manufacturers/<int:pk>/edit/", views.manufacturer_edit, name="admin_manufacturer_edit"),
    path("product-datasheets/", views.product_datasheet_list, name="admin_product_datasheet_list"),
    path("product-datasheets/create/", views.product_datasheet_create, name="admin_product_datasheet_create"),
    path("product-datasheets/<int:pk>/edit/", views.product_datasheet_edit, name="admin_product_datasheet_edit"),
    path("product-datasheets/<int:pk>/delete/", views.product_datasheet_delete, name="admin_product_datasheet_delete"),
    path("facilities/", views.facility_list, name="admin_facility_list"),
    path("facilities/add/", views.facility_add, name="admin_facility_add"),
    path("facilities/<slug:slug>/", views.facility_detail, name="admin_facility_detail"),
    path("facilities/<slug:slug>/edit/", views.facility_edit, name="admin_facility_edit"),
    path("facilities/<slug:slug>/delete/", views.facility_delete, name="admin_facility_delete"),
    path("facilities/<slug:facility_slug>/modal-close/", views.facility_modal_close, name="admin_facility_modal_close"),
    path("facilities/<slug:facility_slug>/devices/choose-type/", views.facility_device_choose_type, name="admin_facility_device_choose_type"),
    path("facilities/<slug:facility_slug>/customers/", views.facility_customers_edit, name="admin_facility_customers_edit"),
    path("facilities/<slug:facility_slug>/customers/add/", views.facility_customer_add, name="admin_facility_customer_add"),
    path("facilities/<slug:facility_slug>/customers/<int:customer_id>/remove/", views.facility_customer_remove, name="admin_facility_customer_remove"),
    # Racks
    path("facilities/<slug:facility_slug>/racks/add/", views.rack_add, name="admin_rack_add"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/", views.rack_detail, name="admin_rack_detail"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/edit/", views.rack_edit, name="admin_rack_edit"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/modal-close/", views.rack_modal_close, name="admin_rack_modal_close"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/delete/", views.rack_delete, name="admin_rack_delete"),
    # Rack Seals
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/seals/add/", views.rack_seal_add, name="admin_rack_seal_add"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/seals/<int:seal_id>/remove/", views.rack_seal_remove, name="admin_rack_seal_remove"),
    # Network Devices
    path("facilities/<slug:facility_slug>/devices/add/", views.network_device_add, name="admin_network_device_add"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/devices/add/", views.network_device_add, name="admin_network_device_add_to_rack"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/devices/add/<int:rack_position>/", views.network_device_add, name="admin_network_device_add_to_position"),
    path("facilities/<slug:facility_slug>/devices/<int:device_id>/edit/", views.network_device_edit, name="admin_network_device_edit"),
    path("facilities/<slug:facility_slug>/racks/<int:rack_id>/devices/<int:device_id>/remove/", views.network_device_remove_from_rack, name="admin_network_device_remove_from_rack"),
    path("facilities/<slug:facility_slug>/devices/<int:device_id>/delete/", views.network_device_delete, name="admin_network_device_delete"),
    # IP Addresses
    path("facilities/<slug:facility_slug>/ip/add/", views.ip_address_add, name="admin_ip_address_add"),
    path("facilities/<slug:facility_slug>/ip/<int:ip_id>/edit/", views.ip_address_edit, name="admin_ip_address_edit"),
    path("facilities/<slug:facility_slug>/ip/<int:ip_id>/delete/", views.ip_address_delete, name="admin_ip_address_delete"),
    # Facility Documents
    path("facilities/<slug:facility_slug>/documents/upload/", views.facility_document_upload, name="admin_facility_document_upload"),
    path("facilities/<slug:facility_slug>/documents/<int:doc_id>/delete/", views.facility_document_delete, name="admin_facility_document_delete"),
    path("facilities/<slug:facility_slug>/contacts/add/", views.facility_contact_add, name="admin_facility_contact_add"),
    path("facilities/<slug:facility_slug>/contacts/<int:contact_id>/edit/", views.facility_contact_edit, name="admin_facility_contact_edit"),
    path("facilities/<slug:facility_slug>/contacts/<int:contact_id>/delete/", views.facility_contact_delete, name="admin_facility_contact_delete"),
    # Facility Service Log
    path("facilities/<slug:facility_slug>/service-log/add/", views.facility_service_log_add, name="admin_facility_service_log_add"),
    path("facilities/<slug:facility_slug>/service-log/<int:log_id>/edit/", views.facility_service_log_edit, name="admin_facility_service_log_edit"),
    path("facilities/<slug:facility_slug>/service-log/<int:log_id>/delete/", views.facility_service_log_delete, name="admin_facility_service_log_delete"),
    path("facilities/<slug:facility_slug>/service-log/<int:log_id>/attachments/upload/", views.facility_service_log_attachment_upload, name="admin_facility_service_log_attachment_upload"),
    path("facilities/<slug:facility_slug>/service-log/<int:log_id>/attachments/<int:attachment_id>/delete/", views.facility_service_log_attachment_delete, name="admin_facility_service_log_attachment_delete"),
    path("facilities/<slug:facility_slug>/service-log/export/", views.facility_service_log_export, name="admin_facility_service_log_export"),
    path("facilities/<slug:facility_slug>/service-log/<int:log_id>/pdf/", views.facility_service_log_pdf_single, name="admin_facility_service_log_pdf_single"),
    # Document templates (master PDF: HTML + CSS → WeasyPrint)
    path("document-templates/", views.document_template_list, name="admin_document_template_list"),
    path("document-templates/add/", views.document_template_add, name="admin_document_template_add"),
    path("document-templates/load-default/<str:document_type>/", views.document_template_load_default, name="admin_document_template_load_default"),
    path("document-templates/<int:pk>/edit/", views.document_template_edit, name="admin_document_template_edit"),
    path("document-templates/<int:pk>/preview/", views.document_template_preview, name="admin_document_template_preview"),
    path("document-templates/<int:pk>/delete/", views.document_template_delete, name="admin_document_template_delete"),
    # Service Types
    path("service-types/", views.service_type_list, name="admin_service_type_list"),
    path("service-types/add/", views.service_type_add, name="admin_service_type_add"),
    path("service-types/<int:pk>/edit/", views.service_type_edit, name="admin_service_type_edit"),
    # Service Visits
    path("facilities/<slug:facility_slug>/service-visits/", views.facility_service_visit_list, name="admin_facility_service_visit_list"),
    path("facilities/<slug:facility_slug>/service-visits/add/", views.facility_service_visit_add, name="admin_facility_service_visit_add"),
    path("facilities/<slug:facility_slug>/service-visits/<int:visit_id>/edit/", views.facility_service_visit_edit, name="admin_facility_service_visit_edit"),
    path("facilities/<slug:facility_slug>/service-visits/<int:visit_id>/delete/", views.facility_service_visit_delete, name="admin_facility_service_visit_delete"),
    # Server management (superuser only)
    path("server/backup-restore/", views.backup_restore, name="admin_backup_restore"),
]
