"""
Copyright (c) 2026 5echo.io
Project: PMG Portal
Purpose: Initial migrations for portal models
Path: src/portal/migrations/0001_initial.py
Created: 2026-02-05
Last Modified: 2026-02-05
"""
# Generated by Django 5.0.11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("member", "Member"), ("admin", "Customer Admin")], default="member", max_length=20)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="portal.customer")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "customer")},
            },
        ),
        migrations.CreateModel(
            name="PortalLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.CharField(blank=True, default="", max_length=300)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="portal.customer")),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
    ]
